"""non unique author

Revision ID: 25ab16cf3738
Revises: 48ca632eab88
Create Date: 2023-03-21 23:34:21.615011

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '25ab16cf3738'
down_revision = '48ca632eab88'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('author', schema=None) as batch_op:
        batch_op.drop_index('first_name')
        batch_op.drop_index('last_name')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('author', schema=None) as batch_op:
        batch_op.create_index('last_name', ['last_name'], unique=False)
        batch_op.create_index('first_name', ['first_name'], unique=False)

    # ### end Alembic commands ###
