"""prepping for oauth

Revision ID: d2597a1a228d
Revises: bcb324fcf41d
Create Date: 2023-06-26 10:22:23.249511

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd2597a1a228d'
down_revision = 'bcb324fcf41d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('user_id', sa.String(length=64), nullable=True))
        batch_op.add_column(sa.Column('token', sa.String(length=256), nullable=True))
        batch_op.create_unique_constraint(None, ['token'])
        batch_op.create_unique_constraint(None, ['user_id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')
        batch_op.drop_constraint(None, type_='unique')
        batch_op.drop_column('token')
        batch_op.drop_column('user_id')

    # ### end Alembic commands ###
